spring:
  application:
    name: tlias-web-management
    servlet:
        multipart:
          max-file-size: 10MB      # 单个文件上限
          max-request-size: 100MB  # 整个请求上限

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 1234   # 你的 MySQL root 密码(已验证可连)

mybatis:
  configuration:
    # 开启驼峰命名映射:dept_id -> deptId
    map-underscore-to-camel-case: true
    # 在控制台打印 SQL 日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
